module Filters
  JOB_TITLE_KEYWORDS = [
    /front-?end/,
    /back-?end/,
    /full-?stack/,
    /software/,
    /technical lead/,
    /development engineer/,
    /deployed.{1,28}engineer/,
    /research engineer/,
    /prompt engineer/,
    /mobile (?:engineer|developer)/,
    /infrastructure (?:engineer|architect)/,
    /platform (?:engineer|developer)/,
    /security engineer/,
    /cloud engineer/,
    /network engineer/,
    /reliability engineer/,
    /\bsre engineer/,
    /support engineer/,
    /escalation engineer/,
    /test automation engineer/,
    /gameplay engineer/,
    /developer/,
    /programmer/,
    /\bui\b/,
    /\bux\b/,
    /\bqa\b/,
    /dev-?ops/,
    /\bios\b/,
    /android/,
    /data scientist/,
    /\bml\b/,
    /\bai\b/,
    /machine learning/,
    /blockchain/,
    /game designer/,
    /cybersecurity/,
    /threat detection/,
    /malware/,
    /\bit\b/,
    /technical designer/,
    /\bseo\b/,
    /ruby/,
    /ruby on rails/,
    /python/,
    /django/,
    /\.net\b/,
    /\bc#/,
    /\bc\+\+/,
    /java/,
    /springboot/,
    /kafka/,
    /distributed systems/,
    /server/,
    /golang/,
    /javascript/,
    /\bjs\b/,
    /nodejs/,
    /\breact\b/,
    /jenkins/,
    /terraform\b/,
    /\bci\/cd\b/,
    /database/,
    /\bsql\b/,
    /workflow automation/,
    /\bapi\b/,
    /cloud platform/,
    /cloud ops/,
    /kubernetes/,
    /\baws\b/,
    /google cloud/,
    /\bgcp\b/,
    /linux/,
    /unix/,
    /\btcp\b/
  ]
end
