AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - vendor/bundle/**/*
    - 'spec/**/*' # Exclude all files under the 'spec' directory
Style/SuppressedException:
  Enabled: false
Style/NonLocalExitFromIterator:
  Enabled: false
Style/ShadowingOuterLocalVariable:
  Enabled: false
Style/CollectionLiteralLength:
  Enabled: false
Style/UnreachableLoop:
  Enabled: false
Style/BlockLength:
  Max: 80
Style/ModuleLength:
  Enabled: false
Style/LineLength:
  Enabled: false
Style/ClassLength:
  Enabled: false
Style/MethodLength:
  Enabled: false
Style/PerceivedComplexity:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/RedundantCondition:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
