# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      BING_API_KEY: ${{ secrets.BING_API_KEY }}
      CHROME_EXTENSION_API_KEY: ${{ secrets.CHROME_EXTENSION_API_KEY }}
      CHROME_EXTENSION_ORIGIN: ${{ secrets.CHROME_EXTENSION_ORIGIN }}
      CRUNCHBASE_API_KEY: ${{ secrets.CRUNCHBASE_API_KEY }}
      SCRAPEUP_API_KEY: ${{ secrets.SCRAPEUP_API_KEY }}
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.1.3'
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Create db
        run: bundle exec rails db:create
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rspec
      - name: Upload VCR log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: vcr-log
          path: log/vcr.log

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true

      - name: Lint Ruby files
        run: bundle exec rubocop --parallel

  brakeman:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install Ruby and gems
          uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
          with:
            bundler-cache: true
        - name: Install dependencies
          run: bundle install
        - name: Run Brakeman
          run: bundle exec brakeman -f sarif -o output.sarif.json
          continue-on-error: true
        - name: Upload SARIF
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: output.sarif.json
